---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
```

```{r}
health_survey <- read_csv("data/scottish_health_survey.csv") %>% clean_names()
data_zones <- read_csv("data/Datazone2011lookup.csv") %>% clean_names()
scottish_core_questions <- read_csv("data/scottish_survey_core_questions.csv") %>%  clean_names()

```

```{r}
health_survey %>% 
  distinct(date_code)
```
```{r}
health_survey %>% 
  distinct(measurement)
```
```{r}
health_survey %>% 
  distinct(units)
```

```{r}
health_survey %>% 
  distinct(scottish_health_survey_indicator)
```

```{r}
end_id <- c(15, 16, 17, 19, 20, 22, 24,
            25, 26, 29, 28, 30, 31, 32)
start_substr <- "S080000"
hb_codes <- c()
for (id in  end_id) {
  hb_codes<- c(hb_codes, paste(start_substr, id, sep = ""))
}
hb_names <- c("NHS Ayrshire and Arran",
              "NHS Borders",
              "NHS Dumfries and Galloway",
              "NHS Forth Valley",
              "NHS Grampian",
              "NHS Highland",
              "NHS Lothian",
              "NHS Orkney",
              "NHS Shetland",
              "NHS Western Isles",
              "NHS Fife",
              "NHS Tayside",
              "NHS Greater Glasgow and Clyde",
              "NHS Lanarkshire")
health_board_names <- tibble(
  "health_board" = c(hb_codes),
  "health_board_name" = c(hb_names)
)
```


```{r}

health_survey_hb <- left_join(health_survey, health_board_names, by=c("feature_code" = "health_board"))

health_survey_hb <- health_survey_hb %>% 
  filter(date_code == "2016-2019") %>% 
  filter(measurement == "Percent") %>% 
  filter(str_detect(feature_code, "S08|S92")) %>% 
  filter(str_detect(scottish_health_survey_indicator, "Life satisfaction")) %>% 
   mutate(indicator = 
           recode(scottish_health_survey_indicator, 
                "Life satisfaction: Above the mode (9 to 10-Extremely satisfied)" 
                = "Extremely satisfied",
                "Life satisfaction: Below the mode (0-Extremely dissatisfied to 7)" 
                = "Extremely dissatisfied to below average",
                "Life satisfaction: Mode (8)" 
                = "Satisfied")) %>% 
  mutate(health_board_name = if_else(is.na(health_board_name), "Scotland", health_board_name))




```

```{r}
life_satisfaction_country <- health_survey_hb %>% 
  filter(str_detect(scottish_health_survey_indicator, "Life satisfaction")) %>% 
  filter(str_detect(health_board, "S92")) %>% 
  filter(measurement == "Percent") %>% 
  filter(sex != "All") %>% 
  mutate(indicator = 
           recode(scottish_health_survey_indicator, 
                "Life satisfaction: Above the mode (9 to 10-Extremely satisfied)" = "Extremely satisfied",
                "Life satisfaction: Below the mode (0-Extremely dissatisfied to 7)" = "Extremely dissatisfied to below average",
                "Life satisfaction: Mode (8)" = "Satisfied"))
```

```{r}
life_satisfaction_country %>% 
  ggplot(aes(x = sex, y = value, fill = indicator)) +
  geom_bar(position = "dodge", stat = "identity")
```


```{r}
life_satisfaction_hb <- health_survey_hb %>% 
  filter(str_detect(scottish_health_survey_indicator, "Life satisfaction")) %>% 
  filter(str_detect(health_board, "S08")) %>% 
  filter(measurement == "Percent") %>% 
  filter(sex != "All") %>% 
  mutate(indicator = 
           recode(scottish_health_survey_indicator, 
                "Life satisfaction: Above the mode (9 to 10-Extremely satisfied)" = "Extremely satisfied",
                "Life satisfaction: Below the mode (0-Extremely dissatisfied to 7)" = "Extremely dissatisfied to below average",
                "Life satisfaction: Mode (8)" = "Satisfied")) %>% 
  arrange(indicator, desc(value))
```

```{r}
life_satisfaction_hb %>% 
  ggplot(aes(x = health_board_name, y = value, fill = indicator)) +
  geom_bar(position = "fill", stat = "identity") +
  coord_flip()
```

```{r}
self_assessed_gh_country <- health_survey_hb %>% 
  filter(str_detect(scottish_health_survey_indicator, "Self-assessed")) %>% 
  filter(str_detect(health_board, "S92")) %>% 
  filter(measurement == "Percent") %>% 
  filter(sex == "All")
```

```{r}
self_assessed_gh_country %>% 
  ggplot(aes(x = date_code, y = value, fill = scottish_health_survey_indicator)) +
  geom_bar(position = "dodge", stat = "identity")
```

```{r}
self_assessed_gh_hb <- health_survey_hb %>% 
  filter(str_detect(scottish_health_survey_indicator, "Self-assessed")) %>% 
  filter(str_detect(health_board, "S08")) %>% 
  filter(measurement == "Percent") %>% 
  filter(sex != "All") %>% 
  filter(date_code == "2016-2019")
```

```{r}
self_assessed_gh_hb %>% 
  ggplot(aes(x = health_board_name, y = value, fill = scottish_health_survey_indicator)) +
  geom_bar(position = "fill", stat = "identity") +
  coord_flip()
```


################## Using different data set now.........Scottish Survey Core Questions

```{r}
scottish_core_questions_hb <-
  left_join(scottish_core_questions, health_board_names, 
            by = c("feature_code" = "health_board"))
```

```{r}
gh_country <- scottish_core_questions_hb %>% 
  filter(str_detect(feature_code, "S92")) %>% 
  filter(measurement == "Percent") %>% 
  filter(type_of_tenure == "All") %>% 
  filter(household_type == "All") %>% 
  filter(age == "All") %>% 
  filter(gender == "All") %>% 
  filter(limiting_long_term_physical_or_mental_health_condition == "All") %>% 
  drop_na(date_code)
```

```{r}
gh_country %>% 
  ggplot(aes(x = date_code, y = value, fill = self_assessed_general_health)) +
  geom_bar(position = "fill", stat = "identity")
```

```{r}
gh_health_board <- scottish_core_questions_hb %>% 
  filter(str_detect(feature_code, "S08")) %>% 
  filter(measurement == "Percent") %>% 
  filter(type_of_tenure == "All") %>% 
  filter(household_type == "All") %>% 
  filter(age != "All") %>% 
  filter(limiting_long_term_physical_or_mental_health_condition == "All")
```

```{r}
gh_health_board %>% 
  filter(date_code == 2018) %>% 
  filter(age != "16-64 years") %>% 
  ggplot(aes(x = age, y = value, fill = self_assessed_general_health)) +
  geom_bar(position = "fill", stat = "identity")
```

```{r}
scottish_core_questions_hb %>% 
 filter(str_detect(feature_code, "S92")) %>% 
  filter(measurement == "Percent") %>% 
  filter(type_of_tenure == "All") %>% 
  filter(household_type == "All") %>% 
  filter(age == "All") %>% 
  filter(gender == "All") %>% 
  filter(date_code == "2018") %>% 
  filter(limiting_long_term_physical_or_mental_health_condition != "All") %>% 
  ggplot(aes(x = limiting_long_term_physical_or_mental_health_condition, 
             y = value, 
             fill = self_assessed_general_health)) +
  geom_bar(position = "fill", stat = "identity")
  
```

```{r}
scottish_core_questions_hb %>% 
 filter(str_detect(feature_code, "S92")) %>% 
  filter(measurement == "Percent") %>% 
  filter(type_of_tenure != "All") %>% 
  filter(household_type == "All") %>% 
  filter(age == "All") %>% 
  filter(gender == "All") %>% 
  filter(date_code == "2018") %>% 
  ggplot(aes(x = type_of_tenure, 
             y = value, 
             fill = self_assessed_general_health)) +
  geom_bar(position = "fill", stat = "identity")
```

```{r}
scottish_core_questions_hb %>% 
 filter(str_detect(feature_code, "S92")) %>% 
  filter(measurement == "Percent") %>% 
  filter(type_of_tenure == "All") %>% 
  filter(household_type != "All") %>% 
  filter(age == "All") %>% 
  filter(gender == "All") %>% 
  filter(date_code == "2018") %>% 
  ggplot(aes(x = household_type, 
             y = value, 
             fill = self_assessed_general_health)) +
  geom_bar(position = "fill", stat = "identity")
```
################### LIFE SATISFACTION - Sandboxing ######################################################
```{r}
#Load in required packages for cleaning

library(tidyverse)
library(janitor)

#Load in raw data set

health_survey <- read_csv("data/raw_data/scottish_health_survey.csv") %>% clean_names()

# Create tibble to name health boards

end_id <- c(15, 16, 17, 19, 20, 22, 24,
            25, 26, 29, 28, 30, 31, 32)
start_substr <- "S080000"
hb_codes <- c()
for (id in  end_id) {
  hb_codes<- c(hb_codes, paste(start_substr, id, sep = ""))
}
hb_names <- c("NHS Ayrshire and Arran",
              "NHS Borders",
              "NHS Dumfries and Galloway",
              "NHS Forth Valley",
              "NHS Grampian",
              "NHS Highland",
              "NHS Lothian",
              "NHS Orkney",
              "NHS Shetland",
              "NHS Western Isles",
              "NHS Fife",
              "NHS Tayside",
              "NHS Greater Glasgow and Clyde",
              "NHS Lanarkshire")
health_board_names <- tibble(
  "health_board" = c(hb_codes),
  "health_board_name" = c(hb_names)
)

#Join raw data set with health board codes to allow useof health board name as variable

life_satisfaction <- left_join(
  health_survey, 
  health_board_names, 
  by=c("feature_code" = "health_board"))

#Filter data to narrow down variable choices to health board/Scotland and sex.
#NB other variables already aggregated so totals left in to allow view of "Scotland"
# data and "All" sexes.

life_satisfaction <- life_satisfaction %>% 
  filter(date_code == "2016-2019") %>% 
  filter(measurement == "Percent") %>% 
  filter(str_detect(feature_code, "S08|S92")) %>% 
  filter(str_detect(scottish_health_survey_indicator, "Life satisfaction")) %>% 
  mutate(indicator = 
           recode(scottish_health_survey_indicator, 
                  "Life satisfaction: Above the mode (9 to 10-Extremely satisfied)" 
                  = "Very Satisfied (above mode)",
                  "Life satisfaction: Below the mode (0-Extremely dissatisfied to 7)" 
                  = "Very Dissatisfied (below mode)",
                  "Life satisfaction: Mode (8)" 
                  = "Satisfied (mode)")) %>% 
  mutate(health_board_name = 
           if_else(is.na(health_board_name), "Scotland", health_board_name)) %>% 
  mutate(indicator_factor = factor(indicator, 
                            levels = c("Very Dissatisfied (below mode)",
                                       "Satisfied (mode)",
                                       "Very Satisfied (above mode)"))) %>% 
  arrange(indicator_factor)

#Output cleaned data to csv file

write_csv(life_satisfaction, file = "data/clean_data/life_satisfaction_clean.csv")
```

```{r}
life_satisfaction %>% 
  filter(sex == "Female" | sex == "Male") %>% 
  filter(health_board_name == "Scotland" | health_board_name == "NHS Lanarkshire") %>% 
  ggplot(aes(x = health_board_name, y = value, fill = indicator_factor)) +
      geom_col(position = "dodge", colour = "grey") +
      scale_fill_brewer(palette = 1) +
      labs(y = "% Adults",
           title = "Life Satisfaction") +
      theme(plot.title = element_text(hjust = 0.5, vjust = 1, size=16),
            axis.title.x = element_blank(),
            axis.text.x = element_text(vjust=1,size=10),
            axis.text.y = element_text(hjust=1.5,size=10),
            legend.title = element_blank(),
            legend.position = "bottom",
            legend.spacing.x = unit(1.0, "cm"),
            legend.text = element_text(size = 10),
            panel.grid.major.y = element_blank(),
            plot.background = element_rect(fill = "white", colour = "grey"),
            panel.background = element_rect(fill = "white", colour = "grey"))+
      facet_wrap(~ sex)
```












